name: my_password_app
description: Aplikasi untuk menyimpan password dengan aman

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  get: ^4.1.1
  get_it: ^7.2.0
  google_sign_in: ^5.3.3
  googleapis: ^9.1.0
  local_auth: ^2.1.0
  path_provider: ^2.0.11
  pretty_dio_logger: ^1.1.1
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_app_light.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
