name: my_password_app
description: Aplikasi untuk menyimpan password dengan aman

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: '>=2.18.1 <3.9.0'

dependencies:
  clipboard: ^0.1.3
  encrypt: ^5.0.1
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  local_auth: ^2.1.6
  path_provider: ^2.0.14
  share_plus: ^6.3.1
  shared_preferences: ^2.0.15

dev_dependencies:
  change_app_package_name: ^1.1.0
  dependency_validator: ^3.2.2
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_app_light.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
