// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkn99yek4cn9djHo1EjLeqyNSSpy-VS1Q',
    appId: '1:746846482403:web:2fbad6d4415c881b39bad6',
    messagingSenderId: '746846482403',
    projectId: 'protect-56d92',
    authDomain: 'protect-56d92.firebaseapp.com',
    storageBucket: 'protect-56d92.appspot.com',
    measurementId: 'G-KT6NPNDCHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPa0B-0S0LZLqUbLd1duu-kmoapPFvFA',
    appId: '1:746846482403:android:26f3b36786c30c6f39bad6',
    messagingSenderId: '746846482403',
    projectId: 'protect-56d92',
    storageBucket: 'protect-56d92.appspot.com',
  );
}
